version: 0.4.2-{build}
platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: 1.7.0
install:
  # Rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-$Env:RUST_VERSION-$Env:RUST_INSTALL_TRIPLE.msi"
  - cmd: start /wait msiexec /i rust-$Env:RUST_VERSION-$Env:RUST_INSTALL_TRIPLE.msi INSTALLDIR="$Env:RUST_INSTALL_DIR" /quiet /qn /norestart
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
  - rustc --version
  - cargo --version
build_script:
  #- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo build --verbose
test_script:
  #- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo test --verbose
